# Generated by Django 4.1.2 on 2022-10-14 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subGroup', to='api.workgroup')),
            ],
            options={
                'verbose_name_plural': 'workGroups',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('familyName', models.CharField(default='', max_length=100)),
                ('jobs', models.ManyToManyField(blank=True, related_name='worker', to='api.job')),
                ('workGroups', models.ManyToManyField(blank=True, related_name='worker', to='api.workgroup')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='job', to='api.worker'),
        ),
    ]
