# Generated by Django 4.1.2 on 2022-10-14 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_workgroup_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroup',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subGroup', to='api.workgroup'),
        ),
    ]
