# Generated by Django 4.1.2 on 2022-10-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_worker_jobs_remove_worker_workgroups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workgroup',
            options={},
        ),
        migrations.RemoveField(
            model_name='job',
            name='workers',
        ),
        migrations.RemoveField(
            model_name='workgroup',
            name='workers',
        ),
        migrations.AddField(
            model_name='worker',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='workers', to='api.job'),
        ),
        migrations.AddField(
            model_name='worker',
            name='workGroups',
            field=models.ManyToManyField(blank=True, related_name='workers', to='api.workgroup'),
        ),
    ]
