# Generated by Django 4.1.2 on 2022-10-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_workgroup_options_remove_job_workers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='subGroups',
            field=models.ManyToManyField(blank=True, related_name='parent', to='api.workgroup'),
        ),
    ]
