# Generated by Django 4.1.2 on 2022-10-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_workgroup_subgroups_workgroup_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgroup',
            name='parent',
        ),
        migrations.AddField(
            model_name='workgroup',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subGroups', to='api.workgroup'),
        ),
    ]
