# Generated by Django 4.1.2 on 2022-10-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_workgroup_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgroup',
            name='parent',
        ),
        migrations.AddField(
            model_name='workgroup',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='subGroups', to='api.workgroup'),
        ),
    ]
