# Generated by Django 4.1.2 on 2022-10-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_workgroup_parent_workgroup_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='lastName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
