# Generated by Django 4.1.2 on 2022-10-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_worker_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='lastName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
